---
- name: AWX Deploy VM OS Host
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  # query a list of devices
  - name: Obtain list of devices from NetBox
    debug:
      msg: >
        "Device {{ item.value.display_name }} (ID: {{ item.key }}) was
         manufactured by {{ item.value.device_type.manufacturer.name }}"
    loop: "{{ query('netbox.netbox.nb_lookup', 'devices',
                    api_endpoint='https://ipam.getcard.com.br/',
                    api_filter='role=management tag=Lenovo'),
                    token='3e684fc527174c0a5b22a212aad849919e320881') }}"
