---
- name: AWX Deploy VM & NetBox
  hosts: localhost
  connection: local
  collections:
  - netbox.netbox
  gather_facts: no
  tasks:
  - name: "GET SITES WITH NB_QUERY"
    set_fact:
      sites: "{{ query('netbox.netbox.nb_lookup', 'sites', api_endpoint='https://ipam.getcard.com.br', validate_certs=False, token='3e684fc527174c0a5b22a212aad849919e320881') }}"
  - debug:
      msg: "{{ sites | json_query('[*].value.name') }}"
